### ISSUE TITLE
Docs for the `name` param in importData are confusing

### ISSUE THREAD

**Issue by sararob** [googleapis/nodejs-automl#48]
I'm looking at the docs for `importData` [here](https://cloud.google.com/nodejs/docs/reference/automl/0.1.x/v1beta1.AutoMlClient#importData) (generated [here](https://github.com/googleapis/nodejs-automl/blob/master/src/v1beta1/auto_ml_client.js#L671
)). 

It says it should be a string with the dataset name, but it actually needs to include the project name and region. I figured this out by looking at the code snippet below:

```
var formattedName = client.datasetPath('[PROJECT]', '[LOCATION]', '[DATASET]');
```

So it should be: `projects/$PROJECT/locations/$LOCATION/datasets/$DATASET`. Can we add this to the docs?

**Comment by meredithslota** [comment]
The RPC reference indicates that it only requires dataset name: https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.ImportDataRequest I know the API and the library have changed since this issue was filed so possibly this is no longer an issue? That said, it looks like the v1beta `name` description was identical: https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1beta1#google.cloud.automl.v1beta1.ImportDataRequest 

@sararob Are you still seeing this?
